config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #  Pages routes
  root 'pages#home'
  # match '/contact', to: 'pages#contact', via: 'get'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/document.rb
class Document < ActiveRecord::Base

    attr_accessor :size, :file_type
    before_save :check_file_format_size

    validates :title, presence: true
    validates :data, presence: true
    validates :file_type, presence: true


    def check_file_format_size
        # Accepted file formats
        unless ['.csv', '.jpg', '.gif', '.png', '.jpeg'].include? file_type
            errors.add(:data, "Unsupported file format. Please upload only csv's and images")
            throw(:abort)
        end
        # Accepted file size (< 20MB)
        unless size < 20971520
            errors.add(:data, "File is too big. Please upload a file less than 20MB")
            throw(:abort)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
    def full_title(page_title)
      base_title = "TNM"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/documents/_document_view_partial.html.erb
<% if @document.file_type == '.csv'  %>
  <table>
      <tr>
      <% @headers.each do |header| %>
          <th><%= header %></th>
      <% end %>
      </tr>
      <% @data.each do |row| %>
      <tr>
        <% row.each do |column| %>
          <td><%= column %></td>
        <% end %>
      </tr>
      <% end %>
  </table>
<% else  %> 
  <%= image_tag "data:image/png;base64,#{Base64.encode64(@data).gsub("\n", "")}" %>
<% end %>

app/views/exception_handler/exceptions/show.html.erb
<%= content_tag :div, class: "exception", data: { status: @exception.status, response: @exception.response.to_s.humanize, rails: Rails.version }, onclick: ("location.href=\"#{root_path}\";" if @exception.status == 500 && Rails.application.routes.recognize_path("/")), title: ("Return Home" if @exception.status == 500 && Rails.application.routes.recognize_path("/")) do %>
  <%= content_tag :span, @exception.status == 500 && "<strong>Oops! Something went wrong!</strong>We're now working to fix this!<p>Return home</p>".html_safe || @exception.description.html_safe %>
<% end %>

app/views/layouts/_footer.html.erb
<div class = "footer">
    <!-- BOTTOM MENU -->
    <div class="copyright">&copy; 2020 Sonar</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar" role = "navigation">
    <div class = "container-fluid">
        <!-- <a href="/" class="main-logo"></a> -->
        <ul class="nav navbar-nav pull-left">
            <li><%= link_to root_path do %>
                Sonar
            <% end %>
            </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
            <li><%= link_to admin_root_path do %>
                <span class = "glyphicon glyphicon-pencil"></span> Admin
                <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag 'application', media: 'screen' %>
	<%= javascript_include_tag 'application' %>

	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="google-site-verification" content="Vey2AcN92WhAXmZ3SAcgJ3k3xFelrafnYim0Bh4xeYA">
	<%= render 'layouts/shim' %>
	<!-- <script src="https://jwpsrv.com/library/0Z+OYJqDEeSP7gp+lcGdIw.js"></script>script> -->
	<script src="https://content.jwplatform.com/libraries/ZesOZ3ap.js"></script>
	<%= favicon_link_tag asset_path('sonar_favicon.jpg') %>
</head>
<body class = "small" data-twrr-rendered = "true">

	<%= render 'layouts/header' %>
	<%= yield %>
	<%# <%= debug(params) if Rails.env.development? %>
	<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/exception.html.erb
<!DOCTYPE html>
<html>
  <!-- Head -->
  <head>
    <!-- Info -->
    <%= content_tag :title, "Error - #{@exception.status} (#{@exception.response.to_s.gsub("_", " ").titleize}) | #{Rails.application.class.parent_name.titleize}" %>

    <!-- Styling -->
    <%= stylesheet_link_tag :exception_handler %>
    <%= favicon_link_tag "exception_handler/favicon.ico" %>

    <!-- Auth -->
    <%= csrf_meta_tags %>
  </head>

  <!-- Body -->
  <%= content_tag :body, yield %>

  <!-- Footer -->
  <% if ExceptionHandler.config.try(:social) %>
    <%= content_tag :footer do %>
      <% ExceptionHandler.config.social.each do |k,v| %>
        <%= link_to image_tag("exception_handler/connect/#{k}.png"), ExceptionHandler::Config::SOCIAL[k] + "/" + v, id: k, title: "#{k.to_s.titleize} Feed", target: :blank if v %>
      <% end %>
    <% end %>
  <% end %>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Home')%>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class = "alert aleart-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prevented you from signing up:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_flash_messages.html.erb
	<% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>